INSERT INTO products (code, name, category, brand, type, description) VALUES ('P001', 'MASK ADULT Surgical 3 ply 50''S MEDICOS with box', 'Health Accessories', 'Medicos', 'Hygiene', 'Colour: Blue (ear loop outside, ear loop inside- random assigned), Green, Purple, White, Lime Green, Yellow, Pink');
INSERT INTO products (code, name, category, brand, description) VALUES ('P002', 'Party Cosplay Player Unknown Battlegrounds Clothes Hallowmas PUBG', 'Men''s Clothing', 'No Brand', 'Suitable for adults and children.');
INSERT INTO products (code, name, category, brand, type, description) VALUES ('P003', 'Xiaomi REDMI 8A Official Global Version 5000 mAh battery champion 31 days 2GB+32GB', 'Mobile & Gadgets', 'Xiaomi', 'Mobile Phones', 'Xiaomi Redmi 8A');
INSERT INTO products (code, name, category, brand, type, description) VALUES ('P004', 'Naelofar Sofis - Printed Square', 'Hijab', 'Naelofar', 'Multi Colour Floral', 'Ornate Iris flower composition with intricate growing foliage');
INSERT INTO products (code, name, category, brand, type, description) VALUES ('P005', 'Philips HR2051 / HR2056 / HR2059 Ice Crushing Blender Jar Mill', 'Small Kitchen Appliances', 'Philips', 'Mixers & Blenders', 'Philips HR2051 Blender (350W, 1.25L Plastic Jar, 4 stars stainless steel blade)');
INSERT INTO products (code, name, category, brand, type, description) VALUES ('P006', 'Gemei GM-6005 Rechargeable Trimmer Hair Cutter Machine', 'Hair Styling Tools', 'Gemei', 'Trimmer', 'The GEMEI hair clipper is intended for professional use.');
INSERT INTO products (code, name, category, brand, type, description) VALUES ('P007', 'Oreo Crumb Small Crushed Cookie Pieces 454g', 'Snacks', 'Oreo', 'Biscuits & Cookies', 'Oreo Crumb Small Crushed Cookie Pieces 454g - Retail & Wholesale New Stock Long Expiry!!!');
INSERT INTO products (code, name, category, brand, description) VALUES ('P008', 'Non-contact Infrared Forehead Thermometer ABS', 'Kids Health & Skincare', 'No Brand', 'Non-contact Infrared Forehead Thermometer ABS for Adults and Children with LCD Display Digital');
INSERT INTO products (code, name, category, brand, type, description) VALUES ('P009', 'Nordic Marble Starry Sky Bedding Sets', 'Bedding', 'No Brand', 'Bedding Sheets', 'Printing process: reactive printing. Package：quilt cover ,bed sheet ,pillow case. Not include comforter or quilt.');
INSERT INTO products (code, name, category, brand, type, description) VALUES ('P010', 'Samsung Galaxy Tab A 10.1''', 'Mobile & Gadgets', 'Samsung', 'Tablets', '4GB RAM. - 64GB ROM. - 1.5 ghz Processor. - 10.1 inches LCD Display');
INSERT INTO products (code, name, category, brand, type, description) VALUES ('P011', 'REALME 5 PRO 6+128GB', 'Mobile & Gadgets', 'Realme', 'Mobile Phones', 'REALME 5 PRO 6+128GB');
INSERT INTO products (code, name, category, brand, type, description) VALUES ('P012', 'Nokia 2.3 - Cyan Green', 'Mobile & Gadgets', 'Nokia', 'Mobile Phones', 'Nokia smartphones get 2 years of software upgrades and 3 years of monthly security updates.');
INSERT INTO products (code, name, category, brand, type, description) VALUES ('P013', 'AKEMI Cotton Select Fitted Bedsheet Set - Adore 730TC', 'Bedding', 'Akemi', 'Bedding Sheets', '100% Cotton Twill. Super Single.');
INSERT INTO products (code, name, category, brand, type, description) VALUES ('P014', 'Samsung Note10+ Phone', 'Mobile & Gadgets', 'OEM', 'Mobile Phones', 'OEM Phone Models');
INSERT INTO products (code, name, category, brand, type, description) VALUES ('P015', 'Keknis Basic Wide Long Shawl', 'Hijab', 'No Brand', 'Plain Shawl', '1.8m X 0.7m (+/-). Heavy chiffon (120 gsm).');
INSERT INTO products (code, name, category, brand, type, description) VALUES ('P016', 'Amani Floral Printed Scarf', 'Hijab', 'Amani', 'Printed Scarf', '1.9m X 0.8m (+/-). Lightweight silk. Beautiful floral print.');
INSERT INTO products (code, name, category, brand, type, description) VALUES ('P017', 'Hijra Casual Jersey Hijab', 'Hijab', 'Hijra', 'Jersey Hijab', '1.7m X 0.6m (+/-). Stretchable jersey material. Suitable for everyday wear.');
INSERT INTO products (code, name, category, brand, type, description) VALUES ('P018', 'Lilac Lace Embroidered Shawl', 'Hijab', 'Elegance', 'Embroidered Shawl', '2m X 0.9m (+/-). Soft lace fabric with intricate embroidery. Elegant and stylish.');
INSERT INTO products (code, name, category, brand, type, description) VALUES ('P019', 'Nur Plain Instant Hijab', 'Hijab', 'Nur', 'Instant Hijab', '1.8m X 0.7m (+/-). Easy-to-wear instant hijab. Made from high-quality jersey fabric.');
INSERT INTO products (code, name, category, brand, type, description) VALUES ('P020', 'Safira Printed Chiffon Scarf', 'Hijab', 'Safira', 'Printed Scarf', '1.9m X 0.8m (+/-). Flowy chiffon material with beautiful prints. Suitable for special occasions.');
INSERT INTO products (code, name, category, brand, type, description) VALUES ('P021', 'Zahara Polka Dot Hijab', 'Hijab', 'Zahara', 'Polka Dot Hijab', '1.7m X 0.6m (+/-). Soft and lightweight fabric with polka dot pattern. Trendy and versatile.');
INSERT INTO products (code, name, category, brand, type, description) VALUES ('P022', 'Hanna Silk Blend Shawl', 'Hijab', 'Hanna', 'Silk Blend Shawl', '2m X 0.9m (+/-). Luxurious silk blend fabric. Provides a smooth and comfortable feel.');
INSERT INTO products (code, name, category, brand, type, description) VALUES ('P023', 'Zaraa Pleated Hijab', 'Hijab', 'Zaraa', 'Pleated Hijab', '1.8m X 0.7m (+/-). Pleated design adds texture and volume. Made from premium polyester fabric.');
INSERT INTO products (code, name, category, brand, type, description) VALUES ('P024', 'Rania Embellished Shawl', 'Hijab', 'Rania', 'Embellished Shawl', '1.9m X 0.8m (+/-). Intricate bead and sequin embellishments. Perfect for formal events.');
INSERT INTO products (code, name, category, brand, type, description) VALUES ('P025', 'Nawal Printed Satin Hijab', 'Hijab', 'Nawal', 'Printed Satin Hijab', '1.7m X 0.6m (+/-). Smooth and shiny satin fabric with vibrant prints. Adds a touch of luxury.');
INSERT INTO products (code, name, category, brand, type, description) VALUES ('P026', 'Jasmine Cotton Blend Hijab', 'Hijab', 'Jasmine', 'Cotton Blend Hijab', '2m X 0.9m (+/-). Breathable cotton blend fabric. Ideal for everyday wear.');
INSERT INTO products (code, name, category, brand, type, description) VALUES ('P027', 'Layla Embroidered Silk Shawl', 'Hijab', 'Layla', 'Embroidered Silk', '1.8m X 0.7m (+/-). Soft silk fabric with intricate embroidery. Adds a touch of sophistication.');
INSERT INTO products (code, name, category, brand, type, description) VALUES ('P028', 'Sahara Ombre Chiffon Scarf', 'Hijab', 'Sahara', 'Ombre Chiffon Scarf', '1.9m X 0.8m (+/-). Lightweight chiffon with beautiful ombre effect. Perfect for a trendy look.');
INSERT INTO products (code, name, category, brand, type, description) VALUES ('P029', 'Amira Plain Cotton Hijab', 'Hijab', 'Amira', 'Plain Cotton Hijab', '1.7m X 0.6m (+/-). Soft and comfortable cotton fabric. Versatile and easy to style.');
INSERT INTO products (code, name, category, brand, type, description) VALUES ('P030', 'Firdaus Embellished Shawl', 'Hijab', 'Firdaus', 'Embellished Shawl', '2m X 0.9m (+/-). Intricate bead and sequin embellishments. Perfect for special occasions.');



