CREATE TABLE products (
  id INT AUTO_INCREMENT NOT NULL,
  code VARCHAR2(9) NOT NULL,
  name VARCHAR2(90) NOT NULL,
  category VARCHAR2(28) NOT NULL,
  brand VARCHAR2(28) DEFAULT NULL,
  type VARCHAR2(21) DEFAULT NULL,
  description VARCHAR2(180) DEFAULT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE (code)
);
